spring:
    datasource:
        url: jdbc:postgresql://localhost:4481/postgres
        username: postgres
        password: postgres481
        driver-class-name: org.postgresql.Driver 
    h2:
        console.enabled: false